### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible-network/ansible_collections.ansible.netcommon/pull/4
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/286
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 15a5439b5542d069a57517dc0976da5180304223

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now a6b8064de6f9e3cda98f8484c77ee5cb1f4b0ff3

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d496299bf1f3966366ddc1a6d500a9527289d64c

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now ebcd038972ae5f878c2e43e51f009f3e36f6d592

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now b4bdd8f62f3f60ec5abf1a43e2a73a27b4d53497

**Pull request merged**
