### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible/ansible/pull/60947
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now baebedd8744dda2aa3a638a23471ad35a0b1f381

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 85aedf2e26a97a2fee562bd623874c2bd9fa22bb

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now da9f620ce1b7cb39759a284da046e7eb79a852e5

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 3119e0ebcafb7151e14b2471b9a20000c17f537f

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 0c5bfaabbba49f202a5b2a7c3ef10e266b1eecb1

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 2b0be560d30c4c24620b0ade29bd62b7fbb57b22

**Pull request merged**
