### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/281
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/282
Depends-On: https://github.com/ansible-network/ansible_collections.ansible.netcommon/pull/2
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d3934215e956f16b295d1af6aba6157455defa5c

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now fe259e13fb1959079167133d3ddeacfe0cb70b6c

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d687000c9fcac930c0cb2e44d793b3fb8d8120f0

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 01bf45670c16f9399bae13563c5e5eaf59ee5acb

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now b6c4dfd38b241a4db25e0323c58636dec3ab3946

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 5410a55a6309357fedae9c1e02212cd683780957

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 6399a73b47e9872f509a57de1bed7ef2232a1ea0

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now cd3acf6c72bac37cf57906c62046d018748d3a8d

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now fed9f2945a56aa7bae47b2670e395f4cb81444f2

**Pull request merged**
