### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible-network/ansible_collections.cisco.ios/pull/46
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 361a4d960591e009602f822cf5bb17e9fb143cc9

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now ab645e8449ad515b57fa87cd9fbf608c62336b97

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 93417f529742fd46308627567ec86bab0f501617

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 2275b980f8cb662cbaf77b16754590b02b9c1945

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 0c583f73dc013d7ea57f2deef8636e63339502e4

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 7447e09b52d1b50fd4b9783dfbac9d3d2c1d5647

**Pull request merged**
